[package]
name = "ws_cli"
version = "0.1.1"
edition = "2024"

[dependencies]
futures-channel = "0.3.31"
futures-util = "0.3.31"
tokio = { version = "1.46.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
